
name: angular-testing
extensions:
  - name: dapr
ingress:
  - name: ingress
    bindings:
      - port: 1337
    rules:
      - path: /api/course-catalog
        service: courses-api
      - path: /api/scheduling
        service: schedule-api
      - host: dev.localhost
        service: mongo-express

services:
- name: schedule-api
  project: .\backend\ClassScheduleApi\ClassScheduleApi.csproj
  bindings:
    - port: 1339

- name: courses-api
  project: .\backend\CoursesApi\CoursesApi.csproj
  bindings:
    - port: 1340

# Support 
- name: mongodb
  image: mongo
  env: 
    - name: MONGO_INITDB_ROOT_USERNAME
      value: admin
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: TokyoJoe138!
  bindings:
    - port: 27017
  volumes:
    - source: data/
      target: /data/db

- name: mongo-express
  image: mongo-express
  bindings:
    - containerPort: 8081
      port: 8081
      protocol: http
  env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: admin
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: TokyoJoe138!
    - name: ME_CONFIG_MONGODB_URL
      value: mongodb://admin:TokyoJoe138!@mongodb:27017

